<?php
namespace App\DataFixtures;

use App\DataFixtures\UserFixtures;
use App\DataFixtures\SocietyFixtures;
use App\Entity\ActivatedLanguage;
use App\Entity\TrainingLang;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;

class TrainingLanguageFixture extends Fixture
{
    public const LANGUAGE_REFERENCE_FR = '1';
    public const LANGUAGE_REFERENCE_EN = '1';
    public const LANGUAGE_REFERENCE_ES = '1';
    public const LANGUAGE_REFERENCE_IT = '1';
    public const LANGUAGE_REFERENCE_AL = '1';
    public const LANGUAGE_REFERENCE_AR = '1';
    public const LANGUAGE_REFERENCE_JA = '1';
    public const LANGUAGE_REFERENCE_PT = '1';
    public const LANGUAGE_REFERENCE_RU = '1';
    public const LANGUAGE_REFERENCE_CO = '1';
    public const LANGUAGE_REFERENCE_CHT = '1';
    public const LANGUAGE_REFERENCE_CHS = '1';

    public function load(ObjectManager $manager)
    {
        $en = new TrainingLang();
        $en->setLabelFr("_EN");
        $en->setLabel("English");
        $en->setIsoCode6393('eng');
        $en->setIsoCode6391('en');
        $en->setEncode('UTF-8');
        $en->setPosition(1);
        $en->setImageName("en-flag.png");
        $en->setQuizValidateButtonLabel("Validate");
        $en->setQuizCorrectAnswerTitle("Correct answer(s) :");
        $en->setQuizTruefalseInvalid("Please check an answer.");
        $en->setQuizQcmInvalid("Please check at least one answer.");
        $en->setQuizClozeInvalid("Please fill all the boxes.");
        $en->setQuizNumericInvalid("Please choose a value.");
        $en->setQuizLikertInvalid("Please choose a value.");
        $en->setQuizMatchInvalid("Please select an answer for each item.");
        $en->setQuizConfirmation("Click OK to validate the quiz or Cancel");
        $en->setMatchCategoryTitle("Select an element");
        $en->setFeedbackCorrectLabel("Correct");
        $en->setFeedbackIncorrectLabel("Incorrect");
        $en->setAnswerTrueLabel("True");
        $en->setAnswerFalseLabel("False");
        $en->setLikertLabel("Current rating");
        $en->setLikertNoAnswerLabel("none");
        $en->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_EN, $en);
        $manager->persist($en);

        
        $fr = new TrainingLang();
        $fr->setLabelFr('_FR');
        $fr->setLabel('Français');
        $fr->setIsoCode6393('fra');
        $fr->setIsoCode6391('fr');
        $fr->setEncode('UTF-8');
        $fr->setPosition(2);
        $fr->setImageName("fr-flag.png");
        $fr->setQuizValidateButtonLabel("Valider");
        $fr->setQuizCorrectAnswerTitle("Réponse(s) correcte(s) :");
        $fr->setQuizTruefalseInvalid("Vous devez cocher une réponse.");
        $fr->setQuizQcmInvalid("Vous devez cocher au moins une réponse.");
        $fr->setQuizClozeInvalid("Vous devez remplir toutes les cases.");
        $fr->setQuizNumericInvalid("Vous devez indiquer une valeur.");
        $fr->setQuizLikertInvalid("Vous devez choisir une valeur.");
        $fr->setQuizMatchInvalid("Vous devez sélectionner une réponse pour chaque item.");
        $fr->setQuizConfirmation("Si vous souhaitez valider le questionnaire, cliquez sur OK sinon cliquez sur Annuler");
        $fr->setMatchCategoryTitle("Sélectionnez un élément");
        $fr->setFeedbackCorrectLabel("Correct");
        $fr->setFeedbackIncorrectLabel("Incorrect");
        $fr->setAnswerTrueLabel("Vrai");
        $fr->setAnswerFalseLabel("Faux");
        $fr->setLikertLabel("Note actuelle");
        $fr->setLikertNoAnswerLabel("aucune");
        $fr->setActive("1");
        $this->setReference(self::LANGUAGE_REFERENCE_FR, $fr);
        $manager->persist($fr);

        

        $jp = new TrainingLang();
        $jp->setLabelFr("_JP");
        $jp->setLabel("日本語 (にほんご)");
        $jp->setIsoCode6393('jpn');
        $jp->setIsoCode6391('ja');
        $jp->setEncode('UTF-8');
        $jp->setPosition(3);
        $jp->setImageName("ja-flag.png");
        $jp->setQuizValidateButtonLabel("バリデート");
        $jp->setQuizCorrectAnswerTitle("正解：");
        $jp->setQuizTruefalseInvalid("回答を確認してください。");
        $jp->setQuizQcmInvalid("少なくとも1つの回答を選択してください。");
        $jp->setQuizClozeInvalid("すべてのボックスに記入してください。");
        $jp->setQuizNumericInvalid("値を指定する必要があります。");
        $jp->setQuizLikertInvalid("値を選択してください。");
        $jp->setQuizMatchInvalid("各項目の回答を選択してください。");
        $jp->setQuizConfirmation("クイズを検証したりキャンセルするには、[OK]をクリックします");
        $jp->setMatchCategoryTitle("アイテムを選択");
        $jp->setFeedbackCorrectLabel("正しい");
        $jp->setFeedbackIncorrectLabel("間違った");
        $jp->setAnswerTrueLabel("真");
        $jp->setAnswerFalseLabel("偽");
        $jp->setLikertLabel("現在の評価");
        $jp->setLikertNoAnswerLabel("のどれも");
        $jp->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_JA, $jp);
        $manager->persist($jp);

        $it = new TrainingLang();
        $it->setLabelFr("_IT");
        $it->setLabel("Italiano");
        $it->setIsoCode6393('ita');
        $it->setIsoCode6391('it');
        $it->setEncode('UTF-8');
        $it->setPosition(4);
        $it->setImageName("it-flag.png");
        $it->setQuizValidateButtonLabel("Convalida");
        $it->setQuizCorrectAnswerTitle("Risposte corrette :");
        $it->setQuizTruefalseInvalid("Si prega di controllare una risposta.");
        $it->setQuizQcmInvalid("Si prega di scegliere almeno una risposta.");
        $it->setQuizClozeInvalid("Si prega di riempire tutte le scatole.");
        $it->setQuizNumericInvalid("Devi specificare un valore.");
        $it->setQuizLikertInvalid("Si prega di scegliere un valore.");
        $it->setQuizMatchInvalid("Si prega di selezionare una risposta per ogni articolo.");
        $it->setQuizConfirmation("Fai clic su OK per convalidare il quiz o Annulla");
        $it->setMatchCategoryTitle("Seleziona un oggetto");
        $it->setFeedbackCorrectLabel("Corretto");
        $it->setFeedbackIncorrectLabel("Errato");
        $it->setAnswerTrueLabel("Vero");
        $it->setAnswerFalseLabel("Falso");
        $it->setLikertLabel("Valutazione attuale");
        $it->setLikertNoAnswerLabel("nessuna");
        $it->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_IT, $it);
        $manager->persist($it);

        $es = new TrainingLang();
        $es->setLabelFr("_ES");
        $es->setLabel("Español");
        $es->setIsoCode6393('spa');
        $es->setIsoCode6391('es');
        $es->setEncode('UTF-8');
        $es->setPosition(5);
        $es->setImageName("es-flag.png");
        $es->setQuizValidateButtonLabel("Validar");
        $es->setQuizCorrectAnswerTitle("Respuestas correctas :");
        $es->setQuizTruefalseInvalid("Por favor revisa una respuesta.");
        $es->setQuizQcmInvalid("Por favor, elija al menos una respuesta.");
        $es->setQuizClozeInvalid("Por favor llene todas las casillas.");
        $es->setQuizNumericInvalid("Debes especificar un valor.");
        $es->setQuizLikertInvalid("Por favor, elija un valor.");
        $es->setQuizMatchInvalid("Por favor, seleccione una respuesta para cada artículo.");
        $es->setQuizConfirmation("Haga clic en Aceptar para validar el cuestionario o Cancelar");
        $es->setMatchCategoryTitle("Seleccione un artículo");
        $es->setFeedbackCorrectLabel("Correcto");
        $es->setFeedbackIncorrectLabel("Incorrecto");
        $es->setAnswerTrueLabel("Verdadero");
        $es->setAnswerFalseLabel("Falso");
        $es->setLikertLabel("Calificación actual");
        $es->setLikertNoAnswerLabel("ninguna");
        $es->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_ES, $es);
        $manager->persist($es);

        $de = new TrainingLang();
        $de->setLabelFr("_DE");
        $de->setLabel("Deutsch");
        $de->setIsoCode6393('deu');
        $de->setIsoCode6391('de');
        $de->setEncode('UTF-8');
        $de->setPosition(6);
        $de->setImageName("de-flag.png");
        $de->setQuizValidateButtonLabel("Bestätigen Sie");
        $de->setQuizCorrectAnswerTitle("Juiste antwoorden :");
        $de->setQuizTruefalseInvalid("Controleer een antwoord.");
        $de->setQuizQcmInvalid("Kies alstublieft ten minste één antwoord.");
        $de->setQuizClozeInvalid("Vult u alstublieft alle vakjes in.");
        $de->setQuizNumericInvalid("U moet een waarde opgeven.");
        $de->setQuizLikertInvalid("Kies alstublieft een waarde.");
        $de->setQuizMatchInvalid("Selecteer een antwoord voor elk item.");
        $de->setQuizConfirmation("Klik op OK om de quiz te valideren of op Annuleren");
        $de->setMatchCategoryTitle("Selecteer een item");
        $de->setFeedbackCorrectLabel("Correct");
        $de->setFeedbackIncorrectLabel("Incorrect");
        $de->setAnswerTrueLabel("Richtig");
        $de->setAnswerFalseLabel("Falsch");
        $de->setLikertLabel("Aktuelle Bewertung");
        $de->setLikertNoAnswerLabel("keiner");
        $de->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_AL, $de);
        $manager->persist($de);

        $chS = new TrainingLang();
        $chS->setLabelFr("_CNS");
        $chS->setLabel("中国语文");
        $chS->setIsoCode6393('zho(cns)');
        $chS->setIsoCode6391('zh-Hans');
        $chS->setEncode('UTF-8');
        $chS->setPosition(7);
        $chS->setImageName("ch-flag.png");
        $chS->setQuizValidateButtonLabel("验证");
        $chS->setQuizCorrectAnswerTitle("正确答案 :");
        $chS->setQuizTruefalseInvalid("请检查答案。");
        $chS->setQuizQcmInvalid("请至少选择一个答案。");
        $chS->setQuizClozeInvalid("请填写所有的框。");
        $chS->setQuizNumericInvalid("您必须指定一个值。");
        $chS->setQuizLikertInvalid("请选择一个值。");
        $chS->setQuizMatchInvalid("请为每个项目选择一个答案。");
        $chS->setQuizConfirmation("单击确定以验证测验或取消");
        $chS->setMatchCategoryTitle("选择一个项目");
        $chS->setFeedbackCorrectLabel("正确");
        $chS->setFeedbackIncorrectLabel("不正确");
        $chS->setAnswerTrueLabel("实");
        $chS->setAnswerFalseLabel("假");
        $chS->setLikertLabel("当前评级");
        $chS->setLikertNoAnswerLabel("没有");
        $chS->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_CHS, $chS);
        $manager->persist($chS);

        $chT = new TrainingLang();
        $chT->setLabelFr("_CNT");
        $chT->setLabel("中國語文");
        $chT->setIsoCode6393('zho(cnt)');
        $chT->setIsoCode6391('zh-Hant');
        $chT->setEncode('UTF-8');
        $chT->setPosition(8);
        $chT->setImageName("ch-flag.png");
        $chT->setQuizValidateButtonLabel("驗證");
        $chT->setQuizCorrectAnswerTitle("正確答案 ：");
        $chT->setQuizTruefalseInvalid("請檢查答案。");
        $chT->setQuizQcmInvalid("請至少選擇一個答案。");
        $chT->setQuizClozeInvalid("請填寫所有的框。");
        $chT->setQuizNumericInvalid("您必須指定一個值。");
        $chT->setQuizLikertInvalid("請選擇一個值。");
        $chT->setQuizMatchInvalid("請為每個項目選擇一個答案。");
        $chT->setQuizConfirmation("單擊確定以驗證測驗或取消");
        $chT->setMatchCategoryTitle("選擇一個項目");
        $chT->setFeedbackCorrectLabel("正確");
        $chT->setFeedbackIncorrectLabel("不正確");
        $chT->setAnswerTrueLabel("實");
        $chT->setAnswerFalseLabel("假");
        $chT->setLikertLabel("當前評級");
        $chT->setLikertNoAnswerLabel("沒有");
        $chT->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_CHT, $chT);
        $manager->persist($chT);

        $ru = new TrainingLang();
        $ru->setLabelFr("_RU");
        $ru->setLabel("русский язык");
        $ru->setIsoCode6393('rus');
        $ru->setIsoCode6391('ru');
        $ru->setEncode('UTF-8');
        $ru->setPosition(9);
        $ru->setImageName("ru-flag.png");
        $ru->setQuizValidateButtonLabel("Проверить");
        $ru->setQuizCorrectAnswerTitle("Правильные ответы :");
        $ru->setQuizTruefalseInvalid("Проверьте ответ.");
        $ru->setQuizQcmInvalid("Выберите хотя бы один ответ.");
        $ru->setQuizClozeInvalid("Пожалуйста, заполните все поля.");
        $ru->setQuizNumericInvalid("Вы должны указать значение.");
        $ru->setQuizLikertInvalid("Выберите значение.");
        $ru->setQuizMatchInvalid("Выберите ответ для каждого элемента.");
        $ru->setQuizConfirmation("Нажмите OK, чтобы подтвердить викторину или Отменить");
        $ru->setMatchCategoryTitle("Выберите элемент");
        $ru->setFeedbackCorrectLabel("правильный");
        $ru->setFeedbackIncorrectLabel("неправильный");
        $ru->setAnswerTrueLabel("истинный");
        $ru->setAnswerFalseLabel("ложный");
        $ru->setLikertLabel("текущий рейтинг");
        $ru->setLikertNoAnswerLabel("никто");
        $ru->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_RU, $ru);
        $manager->persist($ru);

        $co = new TrainingLang();
        $co->setLabelFr("_KR");
        $co->setLabel("한국어(韓國語); 조선말(朝鮮語)");
        $co->setIsoCode6393('kor');
        $co->setIsoCode6391('kr');
        $co->setEncode('UTF-8');
        $co->setPosition(9);
        $co->setImageName("co-flag.png");
        $co->setQuizValidateButtonLabel("확인");
        $co->setQuizCorrectAnswerTitle("올바른 답:");
        $co->setQuizTruefalseInvalid("답변을 확인하십시오.");
        $co->setQuizQcmInvalid("하나 이상의 답변을 선택하십시오.");
        $co->setQuizClozeInvalid("모든 상자를 채우십시오.");
        $co->setQuizNumericInvalid("값을 지정해야합니다.");
        $co->setQuizLikertInvalid("값을 선택하십시오.");
        $co->setQuizMatchInvalid("각 항목에 대한 답변을 선택하십시오.");
        $co->setQuizConfirmation("확인을 클릭하여 퀴즈를 확인하거나 취소하십시오.");
        $co->setMatchCategoryTitle("항목 선택");
        $co->setFeedbackCorrectLabel("올바른");
        $co->setFeedbackIncorrectLabel("잘못된");
        $co->setAnswerTrueLabel("참");
        $co->setAnswerFalseLabel("거짓");
        $co->setLikertLabel("현재 등급");
        $co->setLikertNoAnswerLabel("없음");
        $co->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_CO, $co);
        $manager->persist($co);

        $pt = new TrainingLang();
        $pt->setLabelFr("_PT");
        $pt->setLabel("Português");
        $pt->setIsoCode6393('por');
        $pt->setIsoCode6391('pt');
        $pt->setEncode('UTF-8');
        $pt->setPosition(10);
        $pt->setImageName("pt-flag.png");
        $pt->setQuizValidateButtonLabel("Validar");
        $pt->setQuizCorrectAnswerTitle("Respostas corretas:");
        $pt->setQuizTruefalseInvalid("Por favor, verifique uma resposta.");
        $pt->setQuizQcmInvalid("Por favor escolha pelo menos uma resposta.");
        $pt->setQuizClozeInvalid("Por favor, preencha todas as caixas.");
        $pt->setQuizNumericInvalid("Você deve especificar um valor.");
        $pt->setQuizLikertInvalid("Por favor, escolha um valor.");
        $pt->setQuizMatchInvalid("Por favor, selecione uma resposta para cada item.");
        $pt->setQuizConfirmation("Clique em OK para validar o questionário ou Cancelar");
        $pt->setMatchCategoryTitle("Selecione um item");
        $pt->setFeedbackCorrectLabel("Correto");
        $pt->setFeedbackIncorrectLabel("Incorreto");
        $pt->setAnswerTrueLabel("Verdadeiro");
        $pt->setAnswerFalseLabel("Falso");
        $pt->setLikertLabel("classificação atual");
        $pt->setLikertNoAnswerLabel("nenhum");
        $pt->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_PT, $pt);
        $manager->persist($pt);

        $ar = new TrainingLang();
        $ar->setLabelFr("_AR");
        $ar->setLabel("العربية");
        $ar->setIsoCode6393('arb');
        $ar->setIsoCode6391('ar');
        $ar->setEncode('UTF-8');
        $ar->setPosition(11);
        $ar->setImageName("ar-flag.png");
        $ar->setQuizValidateButtonLabel("التحقق من الصحة");
        $ar->setQuizCorrectAnswerTitle("الإجابات الصحيحة :");
        $ar->setQuizTruefalseInvalid("الرجاء اختيار إجابة.");
        $ar->setQuizQcmInvalid("يرجى اختيار إجابة واحدة على الأقل.");
        $ar->setQuizClozeInvalid("يرجى ملء جميع الخانات.");
        $ar->setQuizNumericInvalid("يجب عليك تحديد قيمة.");
        $ar->setQuizLikertInvalid("يرجى اختيار قيمة.");
        $ar->setQuizMatchInvalid("يرجى تحديد إجابة لكل عنصر.");
        $ar->setQuizConfirmation("انقر على موافق للتحقق من صحة الاختبار أو إلغاء");
        $ar->setMatchCategoryTitle("اختر عنصرًا");
        $ar->setFeedbackCorrectLabel("صحيح");
        $ar->setFeedbackIncorrectLabel("غير صحيح");
        $ar->setAnswerTrueLabel("صح");
        $ar->setAnswerFalseLabel("خطأ");
        $ar->setLikertLabel("التصنيف الحالي");
        $ar->setLikertNoAnswerLabel("لا شيء");
        $ar->setActive("0");
        $this->setReference(self::LANGUAGE_REFERENCE_AR, $ar);
        $manager->persist($ar);

        $manager->flush();
    }
}