version: "3"

services:
  nginx:
    build: 
       context: ./docker/nginx
    container_name: 'crea-nginx'
    restart: 'always'
    ports:
      - "8080:8080"
    depends_on:
      - php
    volumes: 
      - ./www:/var/www/html:delegated
      - ./user_data/clients:/home/docker/clients:delegated
      - ./user_data/var:/home/docker/var:delegated
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
  php:
    build:
      context: ./docker/php
    container_name: 'crea-php'
    restart: 'always'
    volumes:
      - ./www:/var/www/html
      - ./user_data/clients:/home/docker/clients:delegated
      - ./user_data/var:/home/docker/var:delegated
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini:delegated
  react:
    build:
      context: ./docker/react
    container_name: 'crea-react'
    restart: 'always'
    ports: 
      - "80:3000"
    depends_on:
      - nginx
      - php
    volumes:
      - ./www/crealearning:/var/www/html